# Generated by Django 5.0.6 on 2024-05-30 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appID', models.CharField(max_length=200)),
                ('userID', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('toTestID', models.CharField(max_length=200)),
                ('tipoID', models.CharField(max_length=200)),
                ('data', models.FileField(default=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'wav', 'mp3'])])),
            ],
        ),
    ]
